#!/usr/bin/env python

"""
Connect by BLEDevice
"""

import asyncio
import platform
import sys

from bleak import BleakClient, BleakScanner
from bleak.exc import BleakError

from bleak import BleakScanner


# locate a device by name
async def scanforname():
    device = await BleakScanner.find_device_by_filter(
        lambda d, ad: d.name and d.name.lower() == wanted_name
    )
    return device

# list the services of a particular device
async def print_services(device):
    async with BleakClient(device) as client:
        svcs = await client.get_services()
        print("Services:")
        for service in svcs:
            print(service)

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} name")
    sys.exit(1)
wanted_name = sys.argv[1].lower()

# first find the device from the name
loop = asyncio.get_event_loop()
devicelist = []
devicelist.append(loop.run_until_complete(scanforname()))
thedevice = devicelist[0]

# now find out what services it has
#loop = asyncio.get_event_loop()
loop.run_until_complete(print_services(thedevice))
